name: Build Cloudreve

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cloudreve with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Yarn
        run: npm install -g yarn
        
      - name: Get version info
        id: vars
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Set environment for GoReleaser
        run: |
          echo "GORELEASER_CURRENT_TAG=${{ steps.vars.outputs.version }}" >> $GITHUB_ENV

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: build --clean --single-target --snapshot

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cloudreve-build
          path: dist/**
